[PHP]
error_reporting = E_ALL & ~E_NOTICE
display_errors = On
log_errors = On
error_log = /var/log/apache2/php-error.log
date.timezone = Asia/Bangkok
default_charset = "UTF-8"
mbstring.internal_encoding = UTF-8

[Session]
session.save_path = "/tmp"

[ mssql ]
mssql.charset = "UTF-8"
mssql.textlimit = 65536
mssql.textsize = 65536
